# Adpated from https://github.com/jorgenschaefer/elpy
language: python

python:
  - 2.7
  - 3.5
  - 3.6

dist: trusty

# While python3.7 is not supported by default dist...
matrix:
    include:
      - sudo: required
        dist: xenial
        python: 3.7
        env: EVM_EMACS=emacs-25.1-travis POETRY_VIRTUALENVS_IN_PROJECT=1
      - sudo: required
        dist: xenial
        python: 3.7
        env: EVM_EMACS=emacs-25.2-travis POETRY_VIRTUALENVS_IN_PROJECT=1
      - sudo: required
        dist: xenial
        python: 3.7
        env: EVM_EMACS=emacs-25.3-travis POETRY_VIRTUALENVS_IN_PROJECT=1

env:
  global:
    - POETRY_VIRTUALENVS_IN_PROJECT=1
  jobs:
    - EVM_EMACS=emacs-25.1-travis
    - EVM_EMACS=emacs-25.2-travis
    - EVM_EMACS=emacs-25.3-travis
    - EVM_EMACS=emacs-26.1-travis
    - EVM_EMACS=emacs-26.2-travis
before_install:
  - source ./travis-evm-cask.sh
  - evm install $EVM_EMACS --use --skip
  # verbose only needed because of cask bug
  - cask --verbose
install:
  - pip install 'poetry'
  - pip install coveralls
script:
  - PYTHONPATH="`pwd`" cask exec ert-runner
